modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="annimath"
version="1.0.0"
displayName=" Annihilation: Aftermath"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Steve, MCreator"

[[dependencies.annimath]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




